In [1]:
pip install google-generativeai

Collecting google-generativeai
  Downloading google_generativeai-0.8.5-py3-none-any.whl.metadata (3.9 kB)
Collecting google-ai-generativelanguage==0.6.15 (from google-generativeai)
  Downloading google_ai_generativelanguage-0.6.15-py3-none-any.whl.metadata (5.7 kB)
Collecting google-api-core (from google-generativeai)
  Downloading google_api_core-2.28.1-py3-none-any.whl.metadata (3.3 kB)
Collecting google-api-python-client (from google-generativeai)
  Downloading google_api_python_client-2.187.0-py3-none-any.whl.metadata (7.0 kB)
Collecting google-auth>=2.15.0 (from google-generativeai)
  Downloading google_auth-2.43.0-py2.py3-none-any.whl.metadata (6.6 kB)
Collecting protobuf (from google-generativeai)
  Downloading protobuf-6.33.2-cp39-abi3-macosx_10_9_universal2.whl.metadata (593 bytes)
Requirement already satisfied: pydantic in /usr/local/lib/python3.11/site-packages (from google-generativeai) (2.12.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/site-packages (from google-generativeai) (4.67.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/site-packages (from google-generativeai) (4.15.0)
Collecting proto-plus<2.0.0dev,>=1.22.3 (from google-ai-generativelanguage==0.6.15->google-generativeai)
  Downloading proto_plus-1.26.1-py3-none-any.whl.metadata (2.2 kB)
Collecting protobuf (from google-generativeai)
  Downloading protobuf-5.29.5-cp38-abi3-macosx_10_9_universal2.whl.metadata (592 bytes)
Collecting googleapis-common-protos<2.0.0,>=1.56.2 (from google-api-core->google-generativeai)
  Downloading googleapis_common_protos-1.72.0-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in /usr/local/lib/python3.11/site-packages (from google-api-core->google-generativeai) (2.32.3)
Collecting grpcio<2.0.0,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai)
  Downloading grpcio-1.76.0-cp311-cp311-macosx_11_0_universal2.whl.metadata (3.7 kB)
Collecting grpcio-status<2.0.0,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai)
  Downloading grpcio_status-1.76.0-py3-none-any.whl.metadata (1.1 kB)
Collecting cachetools<7.0,>=2.0.0 (from google-auth>=2.15.0->google-generativeai)
  Downloading cachetools-6.2.2-py3-none-any.whl.metadata (5.6 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth>=2.15.0->google-generativeai)
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting rsa<5,>=3.1.4 (from google-auth>=2.15.0->google-generativeai)
  Downloading rsa-4.9.1-py3-none-any.whl.metadata (5.6 kB)
INFO: pip is looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.
Collecting grpcio-status<2.0.0,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai)
  Downloading grpcio_status-1.75.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.75.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.74.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.73.1-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.73.0-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.72.2-py3-none-any.whl.metadata (1.1 kB)
  Downloading grpcio_status-1.72.1-py3-none-any.whl.metadata (1.1 kB)
INFO: pip is still looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.
  Downloading grpcio_status-1.71.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2025.11.12)
Collecting pyasn1>=0.1.3 (from rsa<5,>=3.1.4->google-auth>=2.15.0->google-generativeai)
  Downloading pyasn1-0.6.1-py3-none-any.whl.metadata (8.4 kB)
Collecting httplib2<1.0.0,>=0.19.0 (from google-api-python-client->google-generativeai)
  Downloading httplib2-0.31.0-py3-none-any.whl.metadata (2.2 kB)
Collecting google-auth-httplib2<1.0.0,>=0.2.0 (from google-api-python-client->google-generativeai)
  Downloading google_auth_httplib2-0.2.1-py3-none-any.whl.metadata (3.0 kB)
Collecting uritemplate<5,>=3.0.1 (from google-api-python-client->google-generativeai)
  Downloading uritemplate-4.2.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: pyparsing<4,>=3.0.4 in /usr/local/lib/python3.11/site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.5)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/site-packages (from pydantic->google-generativeai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.11/site-packages (from pydantic->google-generativeai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.11/site-packages (from pydantic->google-generativeai) (0.4.2)
Downloading google_generativeai-0.8.5-py3-none-any.whl (155 kB)
Downloading google_ai_generativelanguage-0.6.15-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 2.9 MB/s  0:00:00 eta 0:00:01
Downloading google_api_core-2.28.1-py3-none-any.whl (173 kB)
Downloading google_auth-2.43.0-py2.py3-none-any.whl (223 kB)
Downloading cachetools-6.2.2-py3-none-any.whl (11 kB)
Downloading googleapis_common_protos-1.72.0-py3-none-any.whl (297 kB)
Downloading grpcio-1.76.0-cp311-cp311-macosx_11_0_universal2.whl (11.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 3.1 MB/s  0:00:03 eta 0:00:01
Downloading grpcio_status-1.71.2-py3-none-any.whl (14 kB)
Downloading proto_plus-1.26.1-py3-none-any.whl (50 kB)
Downloading protobuf-5.29.5-cp38-abi3-macosx_10_9_universal2.whl (418 kB)
Downloading rsa-4.9.1-py3-none-any.whl (34 kB)
Downloading pyasn1-0.6.1-py3-none-any.whl (83 kB)
Downloading pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Downloading google_api_python_client-2.187.0-py3-none-any.whl (14.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 3.8 MB/s  0:00:03 eta 0:00:01
Downloading google_auth_httplib2-0.2.1-py3-none-any.whl (9.5 kB)
Downloading httplib2-0.31.0-py3-none-any.whl (91 kB)
Downloading uritemplate-4.2.0-py3-none-any.whl (11 kB)
Installing collected packages: uritemplate, pyasn1, protobuf, httplib2, grpcio, cachetools, rsa, pyasn1-modules, proto-plus, googleapis-common-protos, grpcio-status, google-auth, google-auth-httplib2, google-api-core, google-api-python-client, google-ai-generativelanguage, google-generativeai
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17/17 [google-generativeai]ogle-generativeai]language]
Successfully installed cachetools-6.2.2 google-ai-generativelanguage-0.6.15 google-api-core-2.28.1 google-api-python-client-2.187.0 google-auth-2.43.0 google-auth-httplib2-0.2.1 google-generativeai-0.8.5 googleapis-common-protos-1.72.0 grpcio-1.76.0 grpcio-status-1.71.2 httplib2-0.31.0 proto-plus-1.26.1 protobuf-5.29.5 pyasn1-0.6.1 pyasn1-modules-0.4.2 rsa-4.9.1 uritemplate-4.2.0

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: /usr/local/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install --upgrade google-generativeai

Requirement already satisfied: google-generativeai in /usr/local/lib/python3.11/site-packages (0.8.5)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in /usr/local/lib/python3.11/site-packages (from google-generativeai) (0.6.15)
Requirement already satisfied: google-api-core in /usr/local/lib/python3.11/site-packages (from google-generativeai) (2.28.1)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.11/site-packages (from google-generativeai) (2.187.0)
Requirement already satisfied: google-auth>=2.15.0 in /usr/local/lib/python3.11/site-packages (from google-generativeai) (2.43.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/site-packages (from google-generativeai) (5.29.5)
Requirement already satisfied: pydantic in /usr/local/lib/python3.11/site-packages (from google-generativeai) (2.12.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/site-packages (from google-generativeai) (4.67.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/site-packages (from google-generativeai) (4.15.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.11/site-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.26.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.11/site-packages (from google-api-core->google-generativeai) (1.72.0)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in /usr/local/lib/python3.11/site-packages (from google-api-core->google-generativeai) (2.32.3)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.11/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.76.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.11/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.2)
Requirement already satisfied: cachetools<7.0,>=2.0.0 in /usr/local/lib/python3.11/site-packages (from google-auth>=2.15.0->google-generativeai) (6.2.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/site-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/site-packages (from google-auth>=2.15.0->google-generativeai) (4.9.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/site-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2025.11.12)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python3.11/site-packages (from rsa<5,>=3.1.4->google-auth>=2.15.0->google-generativeai) (0.6.1)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.11/site-packages (from google-api-python-client->google-generativeai) (0.31.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.11/site-packages (from google-api-python-client->google-generativeai) (0.2.1)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.11/site-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: pyparsing<4,>=3.0.4 in /usr/local/lib/python3.11/site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.5)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/site-packages (from pydantic->google-generativeai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.11/site-packages (from pydantic->google-generativeai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.11/site-packages (from pydantic->google-generativeai) (0.4.2)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: /usr/local/opt/python@3.11/bin/python3.11 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

Qué necesitas para usar Gemini
Una cuenta de Google.
Crear una API key de Google AI Studio:
Entra en https://aistudio.google.com
Ve a la sección API Key.
Crea una clave nueva y cópiala.

In [21]:
import google.generativeai as genai
import json
import pandas as pd
import numpy as np

import mysql.connector
from mysql.connector import Error

API_KEY = "AIzaSyA1ptyuM8jrjV0fd33CWumA6Jd3N-Bwr_o"  # pon aquí tu key

genai.configure(api_key=API_KEY)

# Modelo que usaremos (texto estructurado)
GEMINI_MODEL = "gemini-2.5-flash"

In [7]:
def enriquecer_referente_con_gemini(nombre_completo):
    """
    Llama a Gemini para obtener información estructurada sobre una mujer referente.
    Devuelve un dict con:
      - pais_principal
      - campo_principal
      - periodo_historico
      - anio_nacimiento
      - anio_muerte
      - logros_clave
    Si falla, devuelve None.
    """
    
    system_prompt = (
        "Eres un asistente experto en historia de mujeres en ciencia y tecnología. "
        "Tu tarea es devolver SIEMPRE un JSON válido. "
        "No escribas nada fuera del JSON, sin explicaciones, sin markdown."
    )

    user_prompt = f"""
Te doy el nombre de una mujer referente en ciencia/tecnología: "{nombre_completo}".

Devuélveme ÚNICAMENTE un JSON con los siguientes campos (sin texto fuera del JSON):

- pais_principal (string): país o región donde desarrolló su actividad principal (ej: "Estados Unidos", "España", "Francia", etc.)
- campo_principal (string breve): campo principal (ej: "informática", "matemáticas", "física", "biología", "astronomía", "activismo tecnológico", etc.)
- periodo_historico (string breve): época aproximada (ej: "siglo XIX", "siglo XX", "era espacial", "medieval", "siglo XXI", etc.)
- anio_nacimiento (number o null): año de nacimiento si se conoce
- anio_muerte (number o null): año de fallecimiento (null si sigue viva o no se sabe)
- logros_clave (string): resumen breve (2-3 frases máximo) de sus principales logros, en español

No escribas explicaciones, ni texto introductorio, ni markdown, ni ```json```. 
Solo el JSON.

Ejemplo de estructura (NO lo uses como contenido, solo como formato):

{{
  "pais_principal": "Estados Unidos",
  "campo_principal": "informática",
  "periodo_historico": "siglo XX",
  "anio_nacimiento": 1906,
  "anio_muerte": 1992,
  "logros_clave": "Pionera en programación. Desarrolló el primer compilador."
}}

Ahora devuélveme el JSON para: {nombre_completo}
    """.strip()
    
    try:
        model = genai.GenerativeModel(GEMINI_MODEL)
        response = model.generate_content(
            [
                {"role": "user", "parts": system_prompt},
                {"role": "user", "parts": user_prompt},
            ]
        )
    except Exception as e:
        print(f"[ERROR llamando a Gemini para '{nombre_completo}']: {e}")
        return None

    # Gemini devuelve el texto en response.text
    content = response.text.strip()

    # Intentar parsear el contenido como JSON
    try:
        result = json.loads(content)
        return result
    except Exception as e:
        print(f"[ERROR parseando JSON para '{nombre_completo}']: {e}")
        print("Contenido devuelto por Gemini:\n", content)
        return None

In [9]:
# Listar modelos disponibles
for model in genai.list_models():
    if 'generateContent' in model.supported_generation_methods:
        print(model.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash-exp
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.0-flash-lite-preview-02-05
models/gemini-2.0-flash-lite-preview
models/gemini-exp-1206
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-3-1b-it
models/gemma-3-4b-it
models/gemma-3-12b-it
models/gemma-3-27b-it
models/gemma-3n-e4b-it
models/gemma-3n-e2b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image-preview
models/gemini-2.5-flash-image
models/gemini-2.5-flash-preview-09-2025
models/gemini-2.5-flash-lite-preview-09-2025
models/gemini-3-pro-preview
models/gemini-3-pro-image-preview
models/nano-banana-pro-preview
models/gemini-robotics-er-1.5-preview
models/gemini-2.5-computer-use-preview-10-2025

In [11]:
nombre_test = "Ada Lovelace"
info = enriquecer_referente_con_gemini(nombre_test)
print(json.dumps(info, indent=2, ensure_ascii=False))

{
  "pais_principal": "Reino Unido",
  "campo_principal": "matemáticas",
  "periodo_historico": "siglo XIX",
  "anio_nacimiento": 1815,
  "anio_muerte": 1852,
  "logros_clave": "Reconocida por haber escrito lo que se considera el primer algoritmo destinado a ser procesado por una máquina, la Máquina Analítica de Charles Babbage. Visionó el potencial de las máquinas más allá del cálculo, sentando las bases de la programación."
}

In [16]:
# Ruta del CSV base
CSV_INPUT = "promos.csv"
df = pd.read_csv(CSV_INPUT)
print(f"Total de promos: {len(df)}")
df.head()

Total de promos: 61

,Nr de la promoción,Año de comienzo,Año de fin,Tipo,Modalidad,Nombre,Nombre de la mujer referente
0,1,2016,2017,PW,Full-time,Ada,Ada Lovelace
1,2,2017,2017,PW,Full-time,Borg,Anita Borg
2,3,2017,2018,PW,Full-time,Clarke,Joan Clarke
3,4,2018,2018,PW,Full-time,Dorcas,Dorcas Muthoni
4,5,2018,2019,PW,Full-time,Easley,Annie Easley

In [17]:
# Creamos columnas nuevas vacías
df["pais_principal"] = None
df["campo_principal"] = None
df["periodo_historico"] = None
df["anio_nacimiento"] = None
df["anio_muerte"] = None
df["logros_clave"] = None

for idx, row in df.iterrows():
    nombre_completo = row["Nombre de la mujer referente"]
    print(f"Procesando: {nombre_completo}...")
    
    info = enriquecer_referente_con_gemini(nombre_completo)
    
    if info is None:
        print(f"  ⚠️ No se pudo obtener información para '{nombre_completo}'.")
        continue
    # .at[] es un método de pandas para acceder/modificar una celda específica de forma rápida.
    df.at[idx, "pais_principal"] = info.get("pais_principal")
    df.at[idx, "campo_principal"] = info.get("campo_principal")
    df.at[idx, "periodo_historico"] = info.get("periodo_historico")
    df.at[idx, "anio_nacimiento"] = info.get("anio_nacimiento")
    df.at[idx, "anio_muerte"] = info.get("anio_muerte")
    df.at[idx, "logros_clave"] = info.get("logros_clave")
    
    print(f"  ✅ OK: {info.get('campo_principal')} | {info.get('pais_principal')}")

Procesando: Ada Lovelace...
  ✅ OK: matemáticas | Reino Unido
Procesando: Anita Borg...
  ✅ OK: informática, activismo tecnológico | Estados Unidos
Procesando: Joan Clarke...
  ✅ OK: criptografía | Reino Unido
Procesando: Dorcas Muthoni...
  ✅ OK: informática y emprendimiento | Kenia
Procesando: Annie Easley...
  ✅ OK: informática y matemáticas | Estados Unidos
Procesando: Mary Fairfax...
  ✅ OK: Matemáticas y Astronomía | Reino Unido
Procesando: Grace Hopper...
  ✅ OK: informática | Estados Unidos
Procesando: Margaret Hamilton...
  ✅ OK: ingeniería de software | Estados Unidos
Procesando: Idelisa Bonnelly...
  ✅ OK: biología marina | República Dominicana
Procesando: Mae Jemison...
  ✅ OK: Astronáutica | Estados Unidos
Procesando: Kizzy Colbert...
  ✅ OK: Desconocido | Estados Unidos
Procesando: Lee Woods...
  ✅ OK: Investigación | Desconocido
Procesando: Mileva Maric...
[ERROR llamando a Gemini para 'Mileva Maric']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 43.903481635s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 43
}
]
  ⚠️ No se pudo obtener información para 'Mileva Maric'.
Procesando: Nerea Luis...
[ERROR llamando a Gemini para 'Nerea Luis']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 43.812743264s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 43
}
]
  ⚠️ No se pudo obtener información para 'Nerea Luis'.
Procesando: Irma Olguin...
[ERROR llamando a Gemini para 'Irma Olguin']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 43.725767354s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 43
}
]
  ⚠️ No se pudo obtener información para 'Irma Olguin'.
Procesando: Paz Gimeno...
[ERROR llamando a Gemini para 'Paz Gimeno']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 43.619355947s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 43
}
]
  ⚠️ No se pudo obtener información para 'Paz Gimeno'.
Procesando: Elena Armada...
[ERROR llamando a Gemini para 'Elena Armada']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 43.539620283s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 43
}
]
  ⚠️ No se pudo obtener información para 'Elena Armada'.
Procesando: Jimena Quirós...
[ERROR llamando a Gemini para 'Jimena Quirós']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 43.40992739s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 43
}
]
  ⚠️ No se pudo obtener información para 'Jimena Quirós'.
Procesando: Katie Bouman...
[ERROR llamando a Gemini para 'Katie Bouman']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 43.330072239s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 43
}
]
  ⚠️ No se pudo obtener información para 'Katie Bouman'.
Procesando: Radia Perlman...
[ERROR llamando a Gemini para 'Radia Perlman']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 43.236730554s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 43
}
]
  ⚠️ No se pudo obtener información para 'Radia Perlman'.
Procesando: Carol Shaw...
[ERROR llamando a Gemini para 'Carol Shaw']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 43.157085966s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 43
}
]
  ⚠️ No se pudo obtener información para 'Carol Shaw'.
Procesando: Margarita Salas...
[ERROR llamando a Gemini para 'Margarita Salas']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 43.069821814s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 43
}
]
  ⚠️ No se pudo obtener información para 'Margarita Salas'.
Procesando: Dorothy Vaughan...
[ERROR llamando a Gemini para 'Dorothy Vaughan']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 42.984159238s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 42
}
]
  ⚠️ No se pudo obtener información para 'Dorothy Vaughan'.
Procesando: Trótula de Salerno...
[ERROR llamando a Gemini para 'Trótula de Salerno']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 42.891017454s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 42
}
]
  ⚠️ No se pudo obtener información para 'Trótula de Salerno'.
Procesando: Evelyn Berezin...
[ERROR llamando a Gemini para 'Evelyn Berezin']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 42.802469703s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 42
}
]
  ⚠️ No se pudo obtener información para 'Evelyn Berezin'.
Procesando: Ursula Martin...
[ERROR llamando a Gemini para 'Ursula Martin']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 42.724156319s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 42
}
]
  ⚠️ No se pudo obtener información para 'Ursula Martin'.
Procesando: Farzana Noorzay...
[ERROR llamando a Gemini para 'Farzana Noorzay']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 42.632527577s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 42
}
]
  ⚠️ No se pudo obtener información para 'Farzana Noorzay'.
Procesando: Alice Augusta Ball...
[ERROR llamando a Gemini para 'Alice Augusta Ball']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 42.547443226s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 42
}
]
  ⚠️ No se pudo obtener información para 'Alice Augusta Ball'.
Procesando: Valentina Tereshkova...
[ERROR llamando a Gemini para 'Valentina Tereshkova']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 42.436074908s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 42
}
]
  ⚠️ No se pudo obtener información para 'Valentina Tereshkova'.
Procesando: Mary Lee Woods...
[ERROR llamando a Gemini para 'Mary Lee Woods']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.
* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash
Please retry in 42.339350491s. [links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.5-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 5
}
, retry_delay {
  seconds: 42
}
]
  ⚠️ No se pudo obtener información para 'Mary Lee Woods'.
Procesando: Sophie Germain...
[ERROR llamando a Gemini para 'Sophie Germain']: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/usage?tab=rate-limit.

In [18]:
df.head()

,Nr de la promoción,Año de comienzo,Año de fin,Tipo,Modalidad,Nombre,Nombre de la mujer referente,pais_principal,campo_principal,periodo_historico,anio_nacimiento,anio_muerte,logros_clave
0,1,2016,2017,PW,Full-time,Ada,Ada Lovelace,Reino Unido,matemáticas,siglo XIX,1815,1852,Es ampliamente reconocida como la primera prog...
1,2,2017,2017,PW,Full-time,Borg,Anita Borg,Estados Unidos,"informática, activismo tecnológico","siglo XX, principios XXI",1949,2003,"Fundó Systers, una de las primeras comunidades..."
2,3,2017,2018,PW,Full-time,Clarke,Joan Clarke,Reino Unido,criptografía,siglo XX,1917,1996,Fue una destacada criptógrafa en Bletchley Par...
3,4,2018,2018,PW,Full-time,Dorcas,Dorcas Muthoni,Kenia,informática y emprendimiento,siglo XXI,1979,None,"Fundadora y CEO de Openworld Ltd., una empresa..."
4,5,2018,2019,PW,Full-time,Easley,Annie Easley,Estados Unidos,informática y matemáticas,era espacial,1933,2011,"Fue una científica informática, matemática y f..."

In [19]:
df.to_csv("promos_referentes_enriquecido.csv", index=False, encoding="utf-8")

In [22]:
try:
    cnx = mysql.connector.connect(
        host='127.0.0.1',
        user='root',
        password='',
    )
    print('Conexión exitosa')
except Error as e:
    print('Error al conectar:', e)

Conexión exitosa

In [24]:
try:
    mycursor = cnx.cursor()
    mycursor.execute("CREATE DATABASE IF NOT EXISTS mujeres_referentes_gemini")
    print("Query exitosa")
except:
    print("Error.")

Query exitosa

In [25]:
# Usar la base de datos
mycursor.execute("USE mujeres_referentes_gemini")

# Crear la tabla si no existe
query = """
CREATE TABLE IF NOT EXISTS mujeres_referentes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nr_promocion INT,
    anio_comienzo INT,
    anio_fin INT,
    tipo VARCHAR(10),
    modalidad VARCHAR(20),
    nombre VARCHAR(50),
    nombre_completo VARCHAR(100),
    pais_principal VARCHAR(100),
    campo_principal VARCHAR(100),
    periodo_historico VARCHAR(50),
    anio_nacimiento INT,
    anio_muerte INT,
    logros_clave TEXT
)
"""

mycursor.execute(query)
cnx.commit()

print("✅ Base de datos 'mujeres_referentes' creada.")
print("✅ Tabla 'mujeres_referentes' lista.")

✅ Base de datos 'mujeres_referentes' creada.
✅ Tabla 'mujeres_referentes' lista.

In [26]:
# Query de inserción
query = """
INSERT INTO mujeres_referentes (
    nr_promocion,
    anio_comienzo,
    anio_fin,
    tipo,
    modalidad,
    nombre,
    nombre_completo,
    pais_principal,
    campo_principal,
    periodo_historico,
    anio_nacimiento,
    anio_muerte,
    logros_clave
) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

# Preparar lista de tuplas con todos los valores

df_clean = df.replace({np.nan: None, 'nan': None, 'NaN': None})

valores_lista = []
for idx, row in df.iterrows():
    valores = (
        int(row["Nr de la promoción"]),
        int(row["Año de comienzo"]),
        int(row["Año de fin"]),
        row["Tipo"],
        row["Modalidad"],
        row["Nombre"],
        row["Nombre de la mujer referente"],
        row["pais_principal"],
        row["campo_principal"],
        row["periodo_historico"],
        int(row["anio_nacimiento"]) if pd.notna(row["anio_nacimiento"]) else None,
        int(row["anio_muerte"]) if pd.notna(row["anio_muerte"]) else None,
        row["logros_clave"]
    )
    valores_lista.append(valores)

# Insertar todas las filas de una vez
mycursor.executemany(query, valores_lista)
cnx.commit()

print(f"🎉 Total de filas insertadas: {mycursor.rowcount}")

🎉 Total de filas insertadas: 61

In [27]:
# O contar cuántas hay en total
mycursor.execute("SELECT COUNT(*) FROM mujeres_referentes")
total = mycursor.fetchone()[0]
print(f"\nTotal de registros en la tabla: {total}")

Total de registros en la tabla: 61