# ETL 
- E: Extract
- T: Transform
- L: Load

In [2]:
import pandas as pd
import mysql.connector 
from mysql.connector import  Error

In [6]:
## Extract (leer de un fichero, llamar a un api, web scrapping,  obtener info de una bd)
clientes = pd.read_csv('files/clientes.csv', index_col=0)
ventas = pd.read_csv('files/ventas.csv')

In [7]:
clientes.head()

,first_name,last_name,email,gender,City,Country,Address
id,,,,,,,
1,Cheri,Dunsmore,cdunsmore0@instagram.com,Female,Palma De Mallorca,Spain,076 Rockefeller Crossing
2,Hunt,Bartomeu,hbartomeu1@nsw.gov.au,Male,Lugo,Spain,0046 Utah Junction
3,Michaeline,Paynton,mpaynton2@narod.ru,Female,NaN,Spain,0 Corry Crossing
4,Filmer,Eirwin,feirwin3@intel.com,NaN,Leon,Spain,5 American Ash Road
5,Tanhya,Lubbock,tlubbock4@huffingtonpost.com,Female,"Hospitalet De Llobregat, L'",Spain,9289 Merry Circle

In [8]:
ventas.head()

   ID_Cliente ID_Producto Fecha_Venta  Cantidad  Total
0         723          A1  2023-11-22         2  17.98
1         498          C3  2023-11-21         1   5.49
2         121          D4  2023-11-20         3  32.97
3         885         L12  2023-11-19         1   6.49
4         347         Q17  2023-11-18         2   7.98

In [9]:
## Transformacion (quitar nulos, calcular categorias, convertir tipo de datos, cambiar nombre de columnas)
clientes.columns = clientes.columns.str.lower()
ventas.columns = ventas.columns.str.lower()

In [ ]:
# LOAD: carga de datos
try: 
    connection = mysql.connector.connect(
        host= '127.0.0.1',
        user= 'root',
        password= '',
        database = 'bd_etl'
    )
    print('conexion exitosa')
except Error as e:
    print(e)


## crear las tablas
## insertar los datos

conexion exitosa

### ETL en funciones

In [16]:
import pandas as pd
import mysql.connector 
from mysql.connector import  Error

## configuracion de la bases de datos
host= '127.0.0.1'
user= 'root'
password= ''
database = 'bd_etl'

def extract_data(file_path):
    print(f'Extrayendo data de {file_path}')
    data = pd.read_csv(file_path)
    print(data.head())
    return data

def transform_data(data):
    print('Transformando')
    data = data.dropna()
    data = data.drop_duplicates()
    data.columns = data.columns.str.lower()
    print(data.head())
    return data

def load_data(data, table_name): 
    try: 
        connection = mysql.connector.connect(
            host= host,
            user=user,
            password= password, 
            database = database
        )
        print('conexion exitosa')
    except Error as e:
        print(e)
    
    cursor = connection.cursor()
    #cursor.execute(f'create table if not exists {table_name}')
    cursor.close()


def proceso_etl():
    
    clientes = extract_data('files/clientes.csv')
    ventas = extract_data('files/ventas.csv')

    clientes_transformed = transform_data(clientes)
    ventas_transformed =  transform_data(ventas)
    
    load_data(clientes_transformed, 'clientes')
    load_data(ventas_transformed, 'ventas')


proceso_etl()

Extrayendo data de files/clientes.csv
   id  first_name last_name                         email  gender  \
0   1       Cheri  Dunsmore      cdunsmore0@instagram.com  Female
1   2        Hunt  Bartomeu         hbartomeu1@nsw.gov.au    Male
2   3  Michaeline   Paynton            mpaynton2@narod.ru  Female
3   4      Filmer    Eirwin            feirwin3@intel.com     NaN
4   5      Tanhya   Lubbock  tlubbock4@huffingtonpost.com  Female

                          City Country                   Address
0            Palma De Mallorca   Spain  076 Rockefeller Crossing
1                         Lugo   Spain        0046 Utah Junction
2                          NaN   Spain          0 Corry Crossing
3                         Leon   Spain       5 American Ash Road
4  Hospitalet De Llobregat, L'   Spain         9289 Merry Circle
Extrayendo data de files/ventas.csv
   ID_Cliente ID_Producto Fecha_Venta  Cantidad  Total
0         723          A1  2023-11-22         2  17.98
1         498          C3  2023-11-21         1   5.49
2         121          D4  2023-11-20         3  32.97
3         885         L12  2023-11-19         1   6.49
4         347         Q17  2023-11-18         2   7.98
Transformando
   id first_name   last_name                         email  gender  \
0   1      Cheri    Dunsmore      cdunsmore0@instagram.com  Female
1   2       Hunt    Bartomeu         hbartomeu1@nsw.gov.au    Male
4   5     Tanhya     Lubbock  tlubbock4@huffingtonpost.com  Female
5   6      Stacy  Minchinton        sminchinton5@ameblo.jp    Male
6   7       Harv      Sandes              hsandes6@who.int    Male

                          city country                   address
0            Palma De Mallorca   Spain  076 Rockefeller Crossing
1                         Lugo   Spain        0046 Utah Junction
4  Hospitalet De Llobregat, L'   Spain         9289 Merry Circle
5            Palma De Mallorca   Spain         4 Meadow Vale Way
6                       Lleida   Spain       20 Menomonie Circle
Transformando
   id_cliente id_producto fecha_venta  cantidad  total
0         723          A1  2023-11-22         2  17.98
1         498          C3  2023-11-21         1   5.49
2         121          D4  2023-11-20         3  32.97
3         885         L12  2023-11-19         1   6.49
4         347         Q17  2023-11-18         2   7.98
conexion exitosa
conexion exitosa

proyecto: 
    - src
        - jupyters
        - data
            - file1
            - file2
        - funciones.py
        - bd.py(creacion bases, insercion, modificascion)
        - queries_bd.py (definicion de las queries)
    main.py