# Pasos generales para hacer una analisis de datos:
1. Pregunta del analisis
2. Obtener los datos: ficheros, bases de dato, apis, web scrapping, etc...
3. Exploracion de datos(EDA)
4. Limpiar y transformación los datos
5. Analisis:
    - Graficos
    - Correlaciones
    - Estadisticas descriptivas
6. Conclusiones

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [ ]:
## funciones de pandas que podemo para obtener información
df.head() # muesra los 5 primeros
df.tail() # muestar los 5 ultimos
df.sample() # devuelve una fila aleatoria
df.columns # ver columnas
df.shape # ver el tamaño del df
df.describe() # ver los estadisticos

In [3]:
df = pd.read_csv('files/bank-additional.csv', index_col=0)
df.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [4]:
df.shape

(43000, 23)

In [5]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'duration', 'campaign', 'pdays', 'previous', 'poutcome',
       'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m',
       'nr.employed', 'y', 'date', 'latitude', 'longitude', 'id_'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43000 entries, 0 to 27570
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             37880 non-null  float64
 1   job             42655 non-null  object
 2   marital         42915 non-null  object
 3   education       41193 non-null  object
 4   default         34019 non-null  float64
 5   housing         41974 non-null  float64
 6   loan            41974 non-null  float64
 7   contact         43000 non-null  object
 8   duration        43000 non-null  int64
 9   campaign        43000 non-null  int64
 10  pdays           43000 non-null  int64
 11  previous        43000 non-null  int64
 12  poutcome        43000 non-null  object
 13  emp.var.rate    43000 non-null  float64
 14  cons.price.idx  42529 non-null  object
 15  cons.conf.idx   43000 non-null  object
 16  euribor3m       33744 non-null  object
 17  nr.employed     43000 non-null  object
 18  y               43000 non-null  object
 19  date            42752 non-null  object
 20  latitude        43000 non-null  float64
 21  longitude       43000 non-null  float64
 22  id_             43000 non-null  object
dtypes: float64(7), int64(4), object(12)
memory usage: 7.9+ MB

In [ ]:
## valores unicos de una columna
df['age'].unique()

array([nan, 57., 37., 40., 56., 45., 59., 24., 25., 41., 29., 35., 54.,
       50., 39., 30., 55., 46., 49., 34., 52., 58., 32., 38., 44., 42.,
       60., 51., 48., 47., 31., 33., 53., 43., 36., 28., 27., 26., 22.,
       20., 23., 21., 61., 19., 18., 70., 66., 76., 67., 73., 88., 95.,
       68., 75., 63., 80., 62., 72., 82., 64., 71., 69., 78., 65., 85.,
       79., 77., 83., 81., 74., 17., 87., 91., 86., 98., 94., 84., 92.,
       89.])

In [ ]:
df.isnull().sum() # saber los nulos

age               5120
job                345
marital             85
education         1807
default           8981
housing           1026
loan              1026
contact              0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx     471
cons.conf.idx        0
euribor3m         9256
nr.employed          0
y                    0
date               248
latitude             0
longitude            0
id_                  0
dtype: int64

In [ ]:
# descripcion estadistica de los datos que son numericos
df.describe().T
# count: cantidad de datos
# mean: media de los valores, suma de los valores/canbtidad
# std: dispersion de los datos
# min: el valor minimo de los daros
## max: la mayor
# percentil 25% 
# percentil 50%
# percentil 75:

,count,mean,std,min,25%,50%,75%,max
age,37880.0,39.977112,10.437957,17.000,32.00000,38.0000,47.00000,98.000
default,34019.0,0.000088,0.009390,0.000,0.00000,0.0000,0.00000,1.000
housing,41974.0,0.535998,0.498708,0.000,0.00000,1.0000,1.00000,1.000
loan,41974.0,0.155620,0.362499,0.000,0.00000,0.0000,0.00000,1.000
duration,43000.0,257.739279,258.666033,0.000,102.00000,179.0000,319.00000,4918.000
campaign,43000.0,2.567233,2.772294,1.000,1.00000,2.0000,3.00000,56.000
pdays,43000.0,962.330953,187.260394,0.000,999.00000,999.0000,999.00000,999.000
previous,43000.0,0.174023,0.497366,0.000,0.00000,0.0000,0.00000,7.000
emp.var.rate,43000.0,0.077128,1.573898,-3.400,-1.80000,1.1000,1.40000,1.400
latitude,43000.0,36.856697,7.225948,24.396,30.61475,36.7610,43.11325,49.384
longitude,43000.0,-95.939067,16.752282,-124.997,-110.49425,-95.8995,-81.42775,-66.937

In [12]:
# descripcion estadistica de los datos que son categoricas(cadenas de texto, string)
df.describe(include="object").T

                count unique                                   top   freq
job             42655     11                                admin.  10873
marital         42915      3                               MARRIED  25999
education       41193      7                     university.degree  12722
contact         43000      2                              cellular  27396
poutcome        43000      3                           NONEXISTENT  37103
cons.price.idx  42529     26                                93,994   7938
cons.conf.idx   43000     26                                 -36,4   8020
euribor3m       33744    309                                 4,857   2287
nr.employed     43000     11                                5228,1  16980
y               43000      2                                    no  38156
date            42752   1860                     4-septiembre-2019     41
id_             43000  43000  089b39d8-e4d0-461b-87d4-814d71e0e079      1

In [13]:
df['marital'].unique()

array(['MARRIED', 'SINGLE', 'DIVORCED', nan], dtype=object)

In [ ]:
df['marital'].value_counts() # no cuenta los nulos

MARRIED     25999
SINGLE      12105
DIVORCED     4811
Name: marital, dtype: int64

In [18]:
df['job'].value_counts(dropna=False)

admin.           10873
blue-collar       9654
technician        7026
services          4162
management        3050
retired           1790
entrepreneur      1522
self-employed     1489
housemaid         1123
unemployed        1063
student            903
NaN                345
Name: job, dtype: int64

In [19]:
df['job'].value_counts(dropna=False, normalize=True)*100

admin.           25.286047
blue-collar      22.451163
technician       16.339535
services          9.679070
management        7.093023
retired           4.162791
entrepreneur      3.539535
self-employed     3.462791
housemaid         2.611628
unemployed        2.472093
student           2.100000
NaN               0.802326
Name: job, dtype: float64

In [20]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'duration', 'campaign', 'pdays', 'previous', 'poutcome',
       'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m',
       'nr.employed', 'y', 'date', 'latitude', 'longitude', 'id_'],
      dtype='object')

In [ ]:
df['cons.price.idx'].value_counts()

In [ ]:
## eliminar columnas
## no me interesan 
# demasiados nulos 
df_new = df.drop(['cons.price.idx', 'cons.conf.idx'], axis= 1) # guardar en nuevo df
df_new.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'duration', 'campaign', 'pdays', 'previous', 'poutcome',
       'emp.var.rate', 'euribor3m', 'nr.employed', 'y', 'date', 'latitude',
       'longitude', 'id_'],
      dtype='object')

In [ ]:
# gestion 
# Identificar los tipos de nulos: NaN, None, 'Null', 9999999 , 00000
# Gestionar esos nulos: eliminar, rellenar (media,mediana) o imputar de forma avanzadaa

In [26]:
df.isnull().sum()

age               5120
job                345
marital             85
education         1807
default           8981
housing           1026
loan              1026
contact              0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx     471
cons.conf.idx        0
euribor3m         9256
nr.employed          0
y                    0
date               248
latitude             0
longitude            0
id_                  0
dtype: int64

In [27]:
df.isna().sum()/df.shape[0]*100

age               11.906977
job                0.802326
marital            0.197674
education          4.202326
default           20.886047
housing            2.386047
loan               2.386047
contact            0.000000
duration           0.000000
campaign           0.000000
pdays              0.000000
previous           0.000000
poutcome           0.000000
emp.var.rate       0.000000
cons.price.idx     1.095349
cons.conf.idx      0.000000
euribor3m         21.525581
nr.employed        0.000000
y                  0.000000
date               0.576744
latitude           0.000000
longitude          0.000000
id_                0.000000
dtype: float64

In [ ]:
# Si tiene mas de 25 -30 % imputo de manera avanzada
# si tiene menos relleno con la media, mediana , moda
# Si tene mas 50% hay que pensar
# Si 1000 personas, y tiene 50% edad la media es 40?
# machne learning, algotitmos lenguaje natural

In [31]:
## Gestion de duplicados
df.duplicated().sum()

0

In [32]:
df.duplicated(subset='date').sum()

41139

In [33]:
##gestion de duplicados
df_tiempo = pd.read_csv('files/data.csv')
df_tiempo

   Day Weather  Temperature  Wind  Humidity
0  Mon   Sunny        12.79    13        30
1  Tue   Sunny        19.67    28        96
2  Wed   Sunny        17.51    16        20
3  Thu  Cloudy        14.44    11        22
4  Fri  Shower        10.51    26        79
5  Sat  Shower        11.07    27        62
6  Sun   Sunny        17.50    20        10

In [34]:
df_tiempo.duplicated().sum()

0

In [ ]:
df_tiempo.duplicated(subset='Weather').sum() # 1, 2, 5, 6

4

In [37]:
df_tiempo.duplicated(subset='Weather', keep='first').sum()

4

In [38]:
df_tiempo.drop_duplicates()

   Day Weather  Temperature  Wind  Humidity
0  Mon   Sunny        12.79    13        30
1  Tue   Sunny        19.67    28        96
2  Wed   Sunny        17.51    16        20
3  Thu  Cloudy        14.44    11        22
4  Fri  Shower        10.51    26        79
5  Sat  Shower        11.07    27        62
6  Sun   Sunny        17.50    20        10

In [ ]:
df_sin_duplicados = df_tiempo.drop_duplicates(subset=['Weather'], keep=False) ## inplace = True para hacerlo sobre el original
df_sin_duplicados

   Day Weather  Temperature  Wind  Humidity
3  Thu  Cloudy        14.44    11        22

In [ ]:
df_copia = df_tiempo ## esto parece copia, es una referencia
df_copia

   Day Weather  Temperature  Wind  Humidity
0  Mon   Sunny        12.79    13        30
1  Tue   Sunny        19.67    28        96
2  Wed   Sunny        17.51    16        20
3  Thu  Cloudy        14.44    11        22
4  Fri  Shower        10.51    26        79
5  Sat  Shower        11.07    27        62
6  Sun   Sunny        17.50    20        10

In [43]:
df_copia.drop_duplicates(subset='Weather', inplace=True)
df_copia

   Day Weather  Temperature  Wind  Humidity
0  Mon   Sunny        12.79    13        30
3  Thu  Cloudy        14.44    11        22
4  Fri  Shower        10.51    26        79

In [44]:
df_tiempo

   Day Weather  Temperature  Wind  Humidity
0  Mon   Sunny        12.79    13        30
3  Thu  Cloudy        14.44    11        22
4  Fri  Shower        10.51    26        79

In [45]:
df_copia_2 = df_tiempo.copy() ## este si copia de verdad
df_copia_2

   Day Weather  Temperature  Wind  Humidity
0  Mon   Sunny        12.79    13        30
3  Thu  Cloudy        14.44    11        22
4  Fri  Shower        10.51    26        79

In [ ]:
df_copia_2.to_csv('files/nuevo_data.csv')